import React, { Suspense } from 'react'

import '@/shared/assets/styles/globals.css'

import { Metadata } from 'next'

import AntdProvider from '@/providers/Antd'
import { StoreProvider } from '@/providers/StoreProvider'
import { Inter } from '@/shared/assets/fonts/fonts'
import { Footer } from '@/widgets/footer/ui/footer'
import { Navbar } from '@/widgets/navbar/ui/navbar'

import Loader from './loading'

export const metadata: Metadata = {
  title: 'RentToolSochi',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="theme-color" content="#1b1d21" />

        <meta name="theme-color" content="#1b1d21" />
      </head>
      <body className={`layout-root ${Inter.className}`}>
        <StoreProvider>
          <AntdProvider>
            <Suspense fallback={<Loader />}>
              <Navbar/>
              <main className="page-content">
                {children}
              </main>
              <Footer/>
            </Suspense>
          </AntdProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
